/*
 * © 2026 Lior Rubinovich. All rights reserved.
 * Unauthorized copying, modification, distribution, or commercial use is prohibited.
 */
// GENERATED by scripts/generateScoredExamples.ts from src/content/scoredExamples.ts - do not edit.
// Numbers from the real scorer, computed at build time; pages read this and never score anything.
// scoredExamples.test.ts regenerates it and fails if it is stale.

export type ScoredExampleRow = { label: string; total: number; shapeMatch: number; coverage: number; smoothness: number; scale: number };

export type ScoredExampleData = {
  path: string;
  shapeId: string;
  partShares: { name: string; percent: number; points: number }[];
  rows: ScoredExampleRow[];
  image: string;
};

export const SCORED_EXAMPLES: ScoredExampleData[] = [
  {
    "path": "/draw-a-perfect-circle",
    "shapeId": "circle",
    "partShares": [
      {
        "name": "The one closed line",
        "percent": 100,
        "points": 128
      }
    ],
    "rows": [
      {
        "label": "The same hand, no mistake",
        "total": 92,
        "shapeMatch": 89,
        "coverage": 100,
        "smoothness": 92,
        "scale": 99
      },
      {
        "label": "Stops 12% short of the join",
        "total": 66,
        "shapeMatch": 54,
        "coverage": 87,
        "smoothness": 93,
        "scale": 100
      },
      {
        "label": "A good circle, drawn at 58% of the size",
        "total": 73,
        "shapeMatch": 89,
        "coverage": 100,
        "smoothness": 92,
        "scale": 58
      }
    ],
    "image": "/images/seo/draw-a-perfect-circle-scored-example.svg"
  },
  {
    "path": "/draw-an-owl-from-memory",
    "shapeId": "ani-owl",
    "partShares": [
      {
        "name": "Body outline, with the ear tufts",
        "percent": 44,
        "points": 56
      },
      {
        "name": "Eyes - both rings and both pupils",
        "percent": 35,
        "points": 44
      },
      {
        "name": "Wings",
        "percent": 12,
        "points": 16
      },
      {
        "name": "Beak",
        "percent": 5,
        "points": 6
      },
      {
        "name": "Feet",
        "percent": 5,
        "points": 6
      }
    ],
    "rows": [
      {
        "label": "The same hand, no mistake",
        "total": 93,
        "shapeMatch": 93,
        "coverage": 98,
        "smoothness": 66,
        "scale": 99
      },
      {
        "label": "Eyes drawn 40% smaller and set wider apart",
        "total": 66,
        "shapeMatch": 55,
        "coverage": 93,
        "smoothness": 66,
        "scale": 99
      }
    ],
    "image": "/images/seo/draw-an-owl-from-memory-scored-example.svg"
  },
  {
    "path": "/draw-a-pig-from-memory",
    "shapeId": "ani-pig",
    "partShares": [
      {
        "name": "Head outline",
        "percent": 42,
        "points": 53
      },
      {
        "name": "Ears",
        "percent": 27,
        "points": 34
      },
      {
        "name": "Snout and nostrils",
        "percent": 24,
        "points": 31
      },
      {
        "name": "Eyes",
        "percent": 8,
        "points": 10
      }
    ],
    "rows": [
      {
        "label": "The same hand, no mistake",
        "total": 88,
        "shapeMatch": 86,
        "coverage": 98,
        "smoothness": 66,
        "scale": 99
      },
      {
        "label": "Snout drawn 40% smaller and higher on the face",
        "total": 61,
        "shapeMatch": 47,
        "coverage": 91,
        "smoothness": 71,
        "scale": 99
      }
    ],
    "image": "/images/seo/draw-a-pig-from-memory-scored-example.svg"
  },
  {
    "path": "/draw-a-snail-from-memory",
    "shapeId": "ani-snail",
    "partShares": [
      {
        "name": "Foot",
        "percent": 33,
        "points": 42
      },
      {
        "name": "Spiral",
        "percent": 30,
        "points": 39
      },
      {
        "name": "Shell outline",
        "percent": 25,
        "points": 32
      },
      {
        "name": "Eye stalks and eyes",
        "percent": 12,
        "points": 15
      }
    ],
    "rows": [
      {
        "label": "The same hand, no mistake",
        "total": 94,
        "shapeMatch": 94,
        "coverage": 98,
        "smoothness": 77,
        "scale": 98
      },
      {
        "label": "Spiral with 1.2 turns instead of 2.2",
        "total": 73,
        "shapeMatch": 64,
        "coverage": 89,
        "smoothness": 75,
        "scale": 98
      }
    ],
    "image": "/images/seo/draw-a-snail-from-memory-scored-example.svg"
  },
  {
    "path": "/draw-a-bear-from-memory",
    "shapeId": "ani-bear",
    "partShares": [
      {
        "name": "Head outline",
        "percent": 44,
        "points": 56
      },
      {
        "name": "Ears",
        "percent": 26,
        "points": 33
      },
      {
        "name": "Muzzle, nose and mouth",
        "percent": 23,
        "points": 30
      },
      {
        "name": "Eyes",
        "percent": 7,
        "points": 9
      }
    ],
    "rows": [
      {
        "label": "The same hand, no mistake",
        "total": 88,
        "shapeMatch": 86,
        "coverage": 100,
        "smoothness": 68,
        "scale": 99
      },
      {
        "label": "Ears smaller, slid outwards and down the sides",
        "total": 64,
        "shapeMatch": 51,
        "coverage": 99,
        "smoothness": 68,
        "scale": 100
      }
    ],
    "image": "/images/seo/draw-a-bear-from-memory-scored-example.svg"
  }
];

export function scoredExampleForPath(path: string): ScoredExampleData | undefined {
  const normalized = path.replace(/\/+$/, "");
  return SCORED_EXAMPLES.find((example) => example.path === normalized);
}
