// Multiplayer admission cost guard - Phase 1: evaluation and measurement only.
//
// Why this exists: on 23 Sep 2026 CYDI exhausted two account-wide Cloudflare Free
// Durable Object caps and production went to edge 429. Analytics could already be
// shed on demand (analyticsBreaker.ts), but multiplayer had NO way to refuse work -
// every optimisation made a room cheaper, none could make fewer rooms. RoomDO was
// 57.2k of the 111.13k DO requests that day.
//
// PHASE 2A ADDS ENFORCEMENT, AND LEAVES IT OFF. `monitorOnly` is the single switch:
// while it is true (the production state) every decision is recorded and then
// ignored, exactly as in phase 1. Set it false and an EMERGENCY policy starts
// actually refusing new room creation for the configured countries - remotely, with
// no deploy and no Android release.
//
// ELEVATED is deliberately NOT enforceable. Percentage admission needs a bucket key
// that is stable per install, and POST /api/room carries no body, no installation id
// and no room code; the only stable input available is IP-derived, which the privacy
// policy rules out. Without one, a person who is refused simply taps Create again and
// re-rolls, so a nominal 50% would not produce anything like a 50% reduction. Rather
// than ship a control that quietly does not work, a config that pairs monitorOnly:
// false with any ELEVATED policy is REJECTED by validation, and if one somehow
// reaches evaluation it falls open. See GUARD_ANDROID_REQUIREMENTS for the client
// change that would make it real.
//
// Three properties this must never violate:
//
//   1. It costs ZERO Durable Object requests. A guard that spends the quota it
//      protects is worse than no guard. There is no DO binding in this file.
//   2. It costs zero KV reads on the hot path. The config is read once per isolate
//      per cache window, exactly like analyticsBreaker.ts.
//   3. It FAILS OPEN. Missing config, malformed config, a KV outage, an unknown
//      country - every one of them resolves to "unrestricted". Guard infrastructure
//      breaking must never be able to take multiplayer down.
//
// Deliberately generic: no country is hard-coded. Iran appears only in tests and in
// the operator's config, because it is the country the 23 Sep data happens to point
// at. Zero, one or many countries can be configured, added or removed without a
// deployment.

import { normalizeCountry, UNKNOWN_COUNTRY } from "./analyticsDO";

export const MULTIPLAYER_GUARD_KV_KEY = "config:multiplayer-guard";

/**
 * The refusal, as a stable contract.
 *
 * 503 rather than 403 or 429: this is temporary capacity protection, not a ban and
 * not a per-client rate limit, and 429 is the status generic HTTP stacks are most
 * likely to retry automatically. Every shipped client (0.50.0 and 0.51.0) funnels any
 * non-ok create response into one manual "please try again" message and performs no
 * automatic retry, so this cannot produce a retry storm today. `code` is here so a
 * future client can recognise the case and say something truer than "try again".
 */
export const GUARD_REJECTION_STATUS = 503;
export const GUARD_REJECTION_CODE = "multiplayer_capacity";
export function guardRejectionBody(): { error: string; code: string; retryable: boolean } {
  return { error: "Play Together is temporarily unavailable. Please try again later.", code: GUARD_REJECTION_CODE, retryable: true };
}

/**
 * What the next Android release must add before ELEVATED percentage enforcement can
 * be made real. Kept next to the code that needs it so the two cannot drift.
 *
 *  1. An anonymous, install-scoped bucket key generated BY CYDI - a random value in
 *     the same family as cydi.installationId.v1, never a hardware or device
 *     identifier, never an advertising id, and never derived from IP.
 *  2. Sent with room creation only (a header or a small JSON body on POST /api/room),
 *     and used for nothing but deterministic admission bucketing.
 *  3. Server-side, ELEVATED then hashes that key so a given install is consistently
 *     inside or outside the admitted share, and tapping Create again cannot re-roll.
 *  4. Dedicated handling of GUARD_REJECTION_CODE: a specific message along the lines
 *     of "Play Together is busy in your area right now - solo play is unaffected",
 *     rather than the current generic create failure.
 *  5. Backoff on that response so a frustrated tapper cannot become the load, with no
 *     automatic retry of room creation at all.
 */
export const GUARD_ANDROID_REQUIREMENTS = "see the comment above - install-scoped bucket key + capacity response handling";

/** Escalating protection levels. Only the operator (or, later, an external monitor) moves between them. */
export const GUARD_MODES = ["NORMAL", "ELEVATED", "EMERGENCY"] as const;
export type GuardMode = (typeof GUARD_MODES)[number];

/** What the guard would do, were it enforcing. Phase 1 records these and allows regardless. */
export const GUARD_DECISIONS = ["would_allow", "would_throttle", "would_reject"] as const;
export type GuardDecision = (typeof GUARD_DECISIONS)[number];

export type CountryPolicy = {
  mode: GuardMode;
  /** ELEVATED only: percentage of new room creations that would be admitted. 0-100. */
  createAllowPercent?: number;
};

export type GuardOverride = {
  /** An ISO country code, or "GLOBAL" to override everything at once. */
  scope: string;
  mode: GuardMode;
  /** ISO timestamp. An override with no future expiry is not accepted - see validate(). */
  expiresAt: string;
  reason?: string;
};

export type MultiplayerGuardConfig = {
  /** The single enforcement switch. True = decide and record only; false = an EMERGENCY policy actually refuses. Production ships true. */
  monitorOnly: boolean;
  globalMode: GuardMode;
  /** Keyed by normalized ISO country code. Absent country = unrestricted. */
  countries: Record<string, CountryPolicy>;
  override?: GuardOverride;
  /** ISO timestamp after which the WHOLE protective state lapses back to NORMAL. */
  expiresAt?: string;
  /** Operator note, surfaced by the status endpoint. */
  reason?: string;
  /** Set by the PUT handler, not by the operator. */
  activatedAt?: string;
  /** Most recent state changes, newest first. Written only on PUT, never per request. */
  history?: GuardTransition[];
};

export type GuardTransition = {
  at: string;
  scope: string;
  from: GuardMode;
  to: GuardMode;
  monitorOnly: boolean;
  reason?: string;
  expiresAt?: string;
};

/** The state the guard resolves to when anything at all is wrong. Unrestricted, always. */
export const GUARD_FAIL_OPEN: MultiplayerGuardConfig = {
  monitorOnly: true,
  globalMode: "NORMAL",
  countries: {},
};

export const MAX_HISTORY_ENTRIES = 20;
/** Same window as the analytics breaker: long enough that the hot path never reads KV, short enough that an operator change lands within a minute. */
const CACHE_MS = 30_000;
const KV_CACHE_TTL_SECONDS = 60;
/** A config carrying more than this many countries is a mistake or an attack, not a policy. */
const MAX_COUNTRIES = 64;

function isGuardMode(value: unknown): value is GuardMode {
  return typeof value === "string" && (GUARD_MODES as readonly string[]).includes(value);
}

function isIsoTimestamp(value: unknown): value is string {
  return typeof value === "string" && value.length >= 20 && Number.isFinite(Date.parse(value));
}

function isPercent(value: unknown): value is number {
  return typeof value === "number" && Number.isInteger(value) && value >= 0 && value <= 100;
}

function isCountryPolicy(value: unknown): value is CountryPolicy {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const p = value as Record<string, unknown>;
  for (const key of Object.keys(p)) if (key !== "mode" && key !== "createAllowPercent") return false;
  if (!isGuardMode(p.mode)) return false;
  if (p.createAllowPercent !== undefined && !isPercent(p.createAllowPercent)) return false;
  return true;
}

function isOverride(value: unknown): value is GuardOverride {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const o = value as Record<string, unknown>;
  for (const key of Object.keys(o)) if (!["scope", "mode", "expiresAt", "reason"].includes(key)) return false;
  // An override is a deliberately temporary thing. One without an expiry is a
  // permanent policy wearing a temporary label, so it is simply not valid here.
  if (!isGuardMode(o.mode) || !isIsoTimestamp(o.expiresAt)) return false;
  if (typeof o.scope !== "string") return false;
  const scope = o.scope.toUpperCase();
  if (scope !== "GLOBAL" && normalizeCountry(scope) === UNKNOWN_COUNTRY) return false;
  if (o.reason !== undefined && typeof o.reason !== "string") return false;
  return true;
}

/**
 * Strict, all-or-nothing validation, matching isValidRemoteAdsConfig's posture: a
 * config that is not exactly right is not partially applied, it is not applied.
 *
 * Callers differ in what they do with a rejection. The PUT handler answers 400 and
 * leaves the stored config alone. The read path falls back to GUARD_FAIL_OPEN, so a
 * corrupted value can never restrict anybody.
 */
export function isValidGuardConfig(value: unknown): value is MultiplayerGuardConfig {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const c = value as Record<string, unknown>;
  const allowed = ["monitorOnly", "globalMode", "countries", "override", "expiresAt", "reason", "activatedAt", "history"];
  for (const key of Object.keys(c)) if (!allowed.includes(key)) return false;

  if (typeof c.monitorOnly !== "boolean") return false;
  if (!isGuardMode(c.globalMode)) return false;
  if (typeof c.countries !== "object" || c.countries === null || Array.isArray(c.countries)) return false;

  const countries = c.countries as Record<string, unknown>;
  const codes = Object.keys(countries);
  if (codes.length > MAX_COUNTRIES) return false;
  for (const code of codes) {
    // Keys must already be normalized, so a policy can never be filed under a code
    // the request path would never produce and then silently never apply.
    if (code !== normalizeCountry(code) || code === UNKNOWN_COUNTRY) return false;
    if (!isCountryPolicy(countries[code])) return false;
  }

  if (c.override !== undefined && !isOverride(c.override)) return false;
  if (c.expiresAt !== undefined && !isIsoTimestamp(c.expiresAt)) return false;
  if (c.reason !== undefined && typeof c.reason !== "string") return false;
  if (c.activatedAt !== undefined && !isIsoTimestamp(c.activatedAt)) return false;
  if (c.history !== undefined && !Array.isArray(c.history)) return false;

  return enforcementConfigError(c as unknown as MultiplayerGuardConfig) === null;
}

/**
 * The extra rules that apply only once monitorOnly is false. Returned as a message
 * rather than a boolean so the PUT handler can tell an operator exactly which rule
 * they hit - "invalid config" on an emergency switch at 2am is not good enough.
 *
 * Monitor-only configs are unconstrained: modelling an ELEVATED policy with no expiry
 * is exactly what phase 1 is for.
 */
export function enforcementConfigError(config: MultiplayerGuardConfig): string | null {
  if (config.monitorOnly) return null;

  // Tolerates a half-formed object: the PUT handler calls this on UNVALIDATED input
  // to explain a rejection, so it must never throw on a missing countries map.
  const policies = typeof config.countries === "object" && config.countries !== null ? Object.values(config.countries) : [];
  const modes = [
    config.globalMode,
    ...policies.map((p) => (p as { mode?: unknown })?.mode),
    ...(config.override ? [config.override.mode] : []),
  ];

  if (modes.includes("ELEVATED")) {
    return "ELEVATED cannot be enforced: percentage admission needs an install-scoped bucket key the client does not send yet. Use monitorOnly:true to model it, or EMERGENCY to actually refuse.";
  }
  // Enforcement without an end is how a temporary capacity measure becomes a
  // permanent geo-block by forgetting. Every live restriction is time-boxed.
  if (modes.includes("EMERGENCY") && config.expiresAt === undefined && config.override?.expiresAt === undefined) {
    return "live EMERGENCY requires expiresAt (prefer the next 00:00 UTC quota reset)";
  }
  return null;
}

/** Parses a stored KV value. Any failure yields null, and the caller falls open. Never throws. */
export function parseGuardConfig(raw: string | null): MultiplayerGuardConfig | null {
  if (raw === null) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  return isValidGuardConfig(parsed) ? parsed : null;
}

// --- isolate cache -------------------------------------------------------------
//
// A KV read per room creation would trade the DO quota for the KV quota - the Free
// plan allows 100,000 KV reads/day, and the breaker already learned this lesson. The
// config is therefore read at most once per isolate per CACHE_MS, with cacheTtl
// asking Cloudflare's edge for the same thing a layer lower.

type GuardKv = { get(key: string, options?: { cacheTtl?: number }): Promise<string | null> };

let cache: { config: MultiplayerGuardConfig; expiresAt: number; fetchedAt: number } | null = null;

/**
 * The current config, or the fail-open default.
 *
 * Only a SUCCESSFUL read is cached. A KV outage therefore retries on the next
 * request rather than freezing an answer for the whole window - and because the
 * fallback is unrestricted, an outage can only ever make the guard less restrictive.
 */
export async function readGuardConfig(kv: GuardKv | undefined, now: number = Date.now()): Promise<MultiplayerGuardConfig> {
  if (cache !== null && now < cache.expiresAt) return cache.config;
  if (!kv) return GUARD_FAIL_OPEN;
  try {
    const raw = await kv.get(MULTIPLAYER_GUARD_KV_KEY, { cacheTtl: KV_CACHE_TTL_SECONDS });
    const config = parseGuardConfig(raw) ?? GUARD_FAIL_OPEN;
    cache = { config, expiresAt: now + CACHE_MS, fetchedAt: now };
    return config;
  } catch {
    return GUARD_FAIL_OPEN;
  }
}

/** How long ago the cached config was read, for the status endpoint. null when nothing is cached. */
export function guardConfigAgeMs(now: number = Date.now()): number | null {
  return cache === null ? null : now - cache.fetchedAt;
}

// --- effective mode ------------------------------------------------------------

export type EffectiveMode = {
  mode: GuardMode;
  /** Where the mode came from, so the status endpoint and logs can explain themselves. */
  source: "override" | "country" | "global" | "expired" | "default";
  createAllowPercent: number;
  expired: boolean;
};

/**
 * Resolve the mode that applies to one country, at one instant.
 *
 * Precedence: a live override beats a country policy, which beats the global mode.
 * Expiry is pure timestamp arithmetic - there is no scheduler in Phase 1, and none is
 * needed: an expired policy simply stops resolving to anything restrictive the moment
 * a request is evaluated after its expiresAt. Nothing is mutated, no cleanup runs, and
 * no write happens because a request noticed the time.
 *
 * The consequence to be honest about: because expiry is lazy, there is no event at
 * exactly 00:00 UTC. Nothing fires, nothing is logged, no history entry appears. The
 * policy just stops applying. A transition record at the boundary needs a scheduler,
 * which is Phase 2.
 */
export function effectiveMode(config: MultiplayerGuardConfig, country: string, now: number = Date.now()): EffectiveMode {
  const unrestricted = (source: EffectiveMode["source"], expired: boolean): EffectiveMode => ({
    mode: "NORMAL",
    source,
    createAllowPercent: 100,
    expired,
  });

  // A country we could not determine is never restricted - see the VPN note in the
  // guard's documentation. ZZ covers absent, XX, Tor and malformed alike.
  if (country === UNKNOWN_COUNTRY) return unrestricted("default", false);

  const wholeConfigExpired = config.expiresAt !== undefined && Date.parse(config.expiresAt) <= now;
  if (wholeConfigExpired) return unrestricted("expired", true);

  const override = config.override;
  if (override && Date.parse(override.expiresAt) > now) {
    const scope = override.scope.toUpperCase();
    if (scope === "GLOBAL" || scope === country) {
      return { mode: override.mode, source: "override", createAllowPercent: override.mode === "ELEVATED" ? 50 : 100, expired: false };
    }
  }

  const policy = config.countries[country];
  if (policy) {
    return {
      mode: policy.mode,
      source: "country",
      createAllowPercent: policy.createAllowPercent ?? (policy.mode === "ELEVATED" ? 50 : 100),
      expired: false,
    };
  }

  if (config.globalMode !== "NORMAL") {
    return { mode: config.globalMode, source: "global", createAllowPercent: 50, expired: false };
  }

  return unrestricted("global", false);
}

// --- admission decision --------------------------------------------------------

export type GuardEvaluation = {
  country: string;
  mode: GuardMode;
  source: EffectiveMode["source"];
  decision: GuardDecision;
  createAllowPercent: number;
  monitorOnly: boolean;
  expired: boolean;
  /** True when this decision is actually being acted on. False whenever monitorOnly is set. */
  enforced: boolean;
  /** The ONLY field the caller may branch on. `decision` is for measurement. */
  allowed: boolean;
};

/**
 * Sampling for ELEVATED.
 *
 * Deliberately a fresh uniform draw per creation attempt rather than a hash of some
 * stable key, because there is nothing stable to hash: POST /api/room carries no body,
 * no installation id and no room code yet. The only stable inputs available would be
 * IP-derived, and CYDI's privacy policy is explicit that it does not use IP.
 *
 * A per-attempt draw gives an unbiased throttle RATE, which is exactly what Phase 1
 * needs to measure. It has a known weakness for enforcement, recorded here so Phase 2
 * does not rediscover it: createRoom() does not retry, but the PERSON does, and each
 * tap re-rolls. At createAllowPercent=50 a determined user is through in about two
 * taps, so the realised reduction in rooms would be well below the nominal 50%.
 * Enforcement therefore needs a bucket key that is stable per device - most cleanly
 * one the client sends deliberately, which is an Android change, not a Worker one.
 */
function sampleAllows(percent: number): boolean {
  if (percent >= 100) return true;
  if (percent <= 0) return false;
  const buf = new Uint32Array(1);
  crypto.getRandomValues(buf);
  return (buf[0] % 100) < percent;
}

/**
 * Evaluate one room-creation attempt.
 *
 * The caller branches on `allowed` and never on `decision`, which keeps measurement
 * and enforcement one concept apart. `allowed` is false in exactly one situation:
 * enforcement is on AND the decision is would_reject, which only EMERGENCY produces.
 *
 * That single condition is what makes ELEVATED unenforceable by construction rather
 * than by remembering - would_throttle can never clear this bar, so even a config
 * that slipped past validation falls open.
 */
export function evaluateRoomCreation(
  config: MultiplayerGuardConfig,
  rawCountry: unknown,
  now: number = Date.now(),
): GuardEvaluation {
  const country = normalizeCountry(rawCountry);
  const eff = effectiveMode(config, country, now);

  let decision: GuardDecision = "would_allow";
  if (eff.mode === "EMERGENCY") decision = "would_reject";
  else if (eff.mode === "ELEVATED" && !sampleAllows(eff.createAllowPercent)) decision = "would_throttle";

  const enforcing = config.monitorOnly !== true;
  // would_reject comes only from EMERGENCY, so would_throttle can never deny.
  const allowed = !(enforcing && decision === "would_reject");

  return {
    country,
    mode: eff.mode,
    source: eff.source,
    decision,
    createAllowPercent: eff.createAllowPercent,
    monitorOnly: config.monitorOnly,
    expired: eff.expired,
    enforced: enforcing && !allowed,
    allowed,
  };
}

/** True when the config would actually refuse somebody right now. Powers the status endpoint's headline. */
export function isEnforcementActive(config: MultiplayerGuardConfig, now: number = Date.now()): boolean {
  if (config.monitorOnly) return false;
  if (config.expiresAt !== undefined && Date.parse(config.expiresAt) <= now) return false;
  const override = config.override;
  if (override && Date.parse(override.expiresAt) > now && override.mode === "EMERGENCY") return true;
  if (Object.values(config.countries).some((p) => p.mode === "EMERGENCY")) return true;
  return config.globalMode === "EMERGENCY";
}

/**
 * Structured one-line record of a decision, for `wrangler tail` / Workers
 * Observability. Deliberately not an analytics event and not a KV or DO write: the
 * monitor must not become the quota problem it was built to watch.
 *
 * Carries no identifying field - country is the coarse network code the analytics
 * pipeline already records, and nothing else about the request is included.
 */
export function guardLogLine(evaluation: GuardEvaluation): string {
  return JSON.stringify({
    t: "mp_guard",
    country: evaluation.country,
    mode: evaluation.mode,
    src: evaluation.source,
    decision: evaluation.decision,
    pct: evaluation.createAllowPercent,
    monitorOnly: evaluation.monitorOnly,
    enforced: evaluation.enforced,
  });
}

/**
 * Placeholder for Phase 2 transition alerting. Intentionally inert and intentionally
 * not wired to anything: no provider, no secret, no account. It exists so the call
 * site can be added to the PUT handler later without reshaping the request path.
 */
export function notifyGuardTransition(_transition: GuardTransition): void {
  // Phase 2: webhook or email, best effort, inside waitUntil, never awaited.
}

/** Test-only: drop the isolate cache between cases. */
export function _resetGuardCacheForTests(): void {
  cache = null;
}
